version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prenava_frontend
    ports:
      - "3000:80" # Map host port 3000 to nginx port 80
    restart: unless-stopped
